package org.example.Exceptions;

public class ex2 {
    // исправленный код
//    try {
//        int [] array = new int[8];// объявляем переменную array
//        int d = 0;
//        double catchedRes1 = int array [8] / d;
//        System.out.println("catchedRes1 = " + catchedRes1);
//    } catch (ArithmeticException e) {
//        throw new ArithmeticException("На ноль делить нельзя!");// выводим ошибку, что делить на ноль нельзя и прекращаем работу.
//    }

}
